language: node_js  #设置语言

node_js: "lts/*"  #设置相应的版本

install:
  - yarn  #安装hexo及插件

before_script:
  - cd themes/sagiri
  - yarn
  - cd ../..

script:
  - hexo cl  #清除
  - hexo g  #生成

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: public
  fqdn: diygod.me
  on:
    branch: master